#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: '{cipher}AQAMgqMfj1finDeqcNX7jwWhudHbUrbR5+n1pwkIoDbfPAZdIqyXDqKYkT3zFI3nVcVX00RJFfOZi9q53aAuZkn7Hp5AhqWAv7vQyzeBipgQ1lm1sBQutz+RCti87gv7+TOhi0hZtG7oJ/dxtlz7tlUVILL4mj9xdsADf69q4Lh5xCdMoWB6PPTf0lGkxMgz3yZQX0+9f5DZ+M80wiNGkGDvhatSvADsV5ImekFhX1xMbP66fJkZmLkiyyApyxsrxUtvD8oj531asvsYVAvxAxWxe59yZ05F3f486bcuMxW7OJcAHyny4sau8Tx2coeSVY5djrLSqOyZPzBid2XK2jSI+wWsWRkef4ycVuqgTgr2XqbswFS9Hqil842TTkQwQs4='
#    url: jdbc:mysql://vcomsmb20.iptime.org:18306/msa-user?characterEncoding=UTF-8&serverTimezone=UTC
#    username: unismb
spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '{cipher}AQAVgDIg7cBghbJ4YzjO14wZfpWOffubBREBpnf/PcSeqV++qbNto4TwPbslXK2ye4tf+W/AysY6M1t9S52UTNcu49DdaHb/w6PsyWoDQOZoWjSSP2bzqnhfC4ZKmIegM7TP3Lm5PGM8qn1pYKQXYdvAjPBdOOiT8en1sdixEDrCBGNxUq3NNii6qr5+hmo0FTgjDGJEUzu5N+N8ApLd+LRXo6VfyVQUeZmfIeFgBOlGU7iiv0CH9gkWyMLB8bL3UxWJDopneFepadgRYcWRrzy1RuS9jJxgwmqN5MW1BsE4WwUtgrDv25dZrELIUjIfQ25CEJ28ncLjpY23FiF3WeJp9jW2IU2hU62JKGlAeM8Y81zAaD8cqHd1mLqbl/oSEf8='
    url: jdbc:mariadb://localhost:3306/vcomcloud
    username: root

gateway:
  ip: 127.0.0.1