token:
  expiration_accessToken_time: 86400000
  expiration_refreshToken_time: 1209600000
  secret: '{cipher}AQAZxJvbr62UH5QR8Rk1jzI2RyfWaCw4JVSqe9wZgAnJsg/OQzcgFTbqqfXJLn1PI6XElud1UvIodoytFoU4vTtahsy/NLst6x67AqeMX701lmEGo0BL5ZVPC+q2Uzm3+OaUr8/Ke+OzPk4P0WlGGdgNUqqHLxhMxNQlLVrUPIOKj7H02bmG43Yn7/ZIm2NOYHE9GZjp6J8nduHkn9o7NjYGwOo/ESMNAYL68hCy5ElpDIXGl5SyoJEiLD/Wshie3a64yv6qZ1C95Ko0781WQTHzd+bF8g8Lq1K2Pw4jE8eDUyur5vn9y9mK9rmvs4vvQu4u/sZa8wxdUbt5TurHjcD0OKDk9efnUiRTvTmeVMEPXGoeSnzERx4g8dnBIoPDDK6ZBMpk0Djw1B7tsSI5AqAiYMi9eD6Cp1kx87Zf+31Ekk0PPNh2+T2ePPnQXQu71U31kyv0o3eezruxsGql1/gJqyrLzlXIG9ayBV5g593M5w=='

spring:
  cloud:
    config:
      allow-override: true
      override-none: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '{cipher}AQAVgDIg7cBghbJ4YzjO14wZfpWOffubBREBpnf/PcSeqV++qbNto4TwPbslXK2ye4tf+W/AysY6M1t9S52UTNcu49DdaHb/w6PsyWoDQOZoWjSSP2bzqnhfC4ZKmIegM7TP3Lm5PGM8qn1pYKQXYdvAjPBdOOiT8en1sdixEDrCBGNxUq3NNii6qr5+hmo0FTgjDGJEUzu5N+N8ApLd+LRXo6VfyVQUeZmfIeFgBOlGU7iiv0CH9gkWyMLB8bL3UxWJDopneFepadgRYcWRrzy1RuS9jJxgwmqN5MW1BsE4WwUtgrDv25dZrELIUjIfQ25CEJ28ncLjpY23FiF3WeJp9jW2IU2hU62JKGlAeM8Y81zAaD8cqHd1mLqbl/oSEf8='
    url: jdbc:mariadb://localhost:3306/vcomcloud
    username: root

#gateway:
#  ip: 172.18.0.9